### PR TITLE
Incorrect magic ?

### PR DESCRIPTION
**Pull request by btuduri**
Hello ,

I'm not sure If I'm wrong but I think this value was incorrect unless if I mistaken.
This document [1] talk about 0x601b for non relocatable executable.

Regards,

[1] https://archive.org/stream/Atari_Linker_ALN_Release_Notes_Jan_24_1990/Atari_Linker_ALN_Release_Notes_Jan_24_1990_djvu.txt

### CODE REVIEW

**Comment by sarnau** [comment]
You are wrong. The TOS image file, has a BRA.S at the beginning. This is not a linker file.

**Comment by btuduri** [comment]
Thank you @sarnau ,

Ah ok, I never seen this BRA (0x602E).
Would you have one or more samples or links so that i can learn more about this magic value ?

Best regards,

**Comment by sarnau** [comment]
Sure, here: [https://github.com/sarnau/AtariSTRomListings/blob/622ccfdd120cdbb9a005b7de84a4562bf9dc28da/TOS206%2C206STBook%2C206.asm#L5](url)

**Comment by btuduri** [comment]
Hello, I can not able to see your link but I dissembled my own atari rom with ida, I understand with you put this magic value ! \o/ Thank you to share with me this knowledge. :)

Thank you @sarnau :)

Best regards,

**Pull request closed without merging**
